
const firebaseConfig={apiKey:"AIzaSyCcpIzXv-6BwVG1omd0djFu7T6FyIoa_pc",authDomain:"aegis-f36a6.firebaseapp.com",projectId:"aegis-f36a6",storageBucket:"aegis-f36a6.firebasestorage.app",messagingSenderId:"492241347617",appId:"1:492241347617:web:07666aadc7c9c8d052ef60"};
firebase.initializeApp(firebaseConfig);
const auth=firebase.auth(),db=firebase.firestore(),storage=firebase.storage();


const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),app={user:null,isOwner:false,chats:[],activeChat:null};
const authScreen=$('#auth-screen'),appEl=$('#app'),sidebar=$('#sidebar'),sidebarOverlay=$('#sidebar-overlay'),chatArea=$('#chat-area'),welcomeState=$('#welcome-state'),messagesContainer=$('#messages-container'),msgInput=$('#msg-input'),btnSend=$('#btn-send'),inputAttachments=$('#input-attachments'),topbarTitle=$('#topbar-title'),userName=$('#user-name'),userRole=$('#user-role'),userAvatar=$('#user-avatar'),userCard=$('#user-card'),userDropdown=$('#user-dropdown'),toastContainer=$('#toast-container');
const ALLOWED_EMAILS=['owner@gmail.com'];
let attachments=[],mediaStream=null,recognition=null;
function toast(msg,type=''){const t=document.createElement('div');t.className=`toast${type?' toast-'+type:''}`;t.textContent=msg;toastContainer.appendChild(t);setTimeout(()=>t.remove(),3500)}
function openModal(id){$('#'+id).classList.remove('hidden')}
function closeModal(id){$('#'+id).classList.add('hidden')}
$$('.modal-backdrop').forEach(b=>b.onclick=()=>b.closest('.modal').classList.add('hidden'));
$$('.modal-close').forEach(b=>b.onclick=()=>b.closest('.modal').classList.add('hidden'));
function toggleSidebar(){sidebar.classList.toggle('open');sidebarOverlay.classList.toggle('hidden')}
$('#btn-toggle-sidebar').onclick=toggleSidebar;
sidebarOverlay.onclick=toggleSidebar;
function enterApp(user){app.user=user;app.isOwner=user.role==='owner';authScreen.classList.add('hidden');appEl.classList.remove('hidden');userName.textContent=user.name;userRole.textContent=user.role;userAvatar.textContent=user.name.charAt(0).toUpperCase();$$('.owner-only').forEach(el=>el.style.display=app.isOwner?'flex':'none');if(app.isOwner)loadUsers();loadChats()}
function fakeAuth(name,email,role){enterApp({name,email,role})}
$('#btn-gmail-auth').onclick=()=>{const email=prompt('Enter Gmail address:');if(!email)return;if(!ALLOWED_EMAILS.includes(email)){toast('Email not authorized','error');return}const name=email.split('@')[0].replace(/[^a-z]/gi,' ').replace(/\b\w/g,c=>c.toUpperCase());fakeAuth(name,email,email===ALLOWED_EMAILS[0]?'owner':'user')};
$('#btn-face-auth').onclick=async()=>{$('#face-scan-overlay').classList.remove('hidden');try{mediaStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'}});$('#face-camera').srcObject=mediaStream;setTimeout(()=>{if(mediaStream){mediaStream.getTracks().forEach(t=>t.stop());$('#face-scan-overlay').classList.add('hidden');fakeAuth('Sharvil','owner@gmail.com','owner')}},3000)}catch(e){toast('Camera access denied','error');$('#face-scan-overlay').classList.add('hidden')}};
$('#btn-cancel-face').onclick=()=>{$('#face-scan-overlay').classList.add('hidden');if(mediaStream){mediaStream.getTracks().forEach(t=>t.stop());mediaStream=null}};
$('#btn-voice-auth').onclick=()=>{$('#voice-scan-overlay').classList.remove('hidden');const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){toast('Speech recognition not supported','error');$('#voice-scan-overlay').classList.add('hidden');return}recognition=new SR();recognition.lang='en-US';recognition.onresult=e=>{const t=e.results[0][0].transcript.toLowerCase();if(t.includes('aegis')||t.includes('hello')){$('#voice-scan-overlay').classList.add('hidden');fakeAuth('Sharvil','owner@gmail.com','owner')}else{toast('Voice not recognized','error');$('#voice-scan-overlay').classList.add('hidden')}};recognition.onerror=()=>{toast('Voice recognition failed','error');$('#voice-scan-overlay').classList.add('hidden')};recognition.start()};
$('#btn-cancel-voice').onclick=()=>{$('#voice-scan-overlay').classList.add('hidden');if(recognition)recognition.abort()};
function loadChats(){const list=$('#chat-history-list');list.innerHTML='';const stored=JSON.parse(localStorage.getItem('aegis_chats')||'[]');app.chats=stored;stored.forEach((c,i)=>{const li=document.createElement('li');li.className=`sidebar-item${app.activeChat===i?' active':''}`;li.textContent=c.title||'New Chat';li.onclick=()=>selectChat(i);list.appendChild(li)});if(!stored.length){list.innerHTML='<li style="padding:10px 12px;font-size:12px;color:var(--text-dim)">No conversations yet</li>'}}
function selectChat(i){app.activeChat=i;const c=app.chats[i];topbarTitle.textContent=c.title||'New Chat';welcomeState.classList.add('hidden');messagesContainer.classList.remove('hidden');renderMessages(c.messages);loadChats()}
function renderMessages(msgs){messagesContainer.innerHTML='';if(!msgs||!msgs.length){messagesContainer.classList.add('hidden');welcomeState.classList.remove('hidden');return}msgs.forEach(m=>appendMessage(m.role,m.content,m.time,false))}
function appendMessage(role,content,time='',animate=true){welcomeState.classList.add('hidden');messagesContainer.classList.remove('hidden');const div=document.createElement('div');div.className=`msg msg-${role}`;if(!animate)div.style.animation='none';const t=time||new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});const name=role==='user'?(app.user?.name||'You'):'Aegis';div.innerHTML=`<div class="msg-avatar">${role==='user'?(app.user?.name||'U').charAt(0):'A'}</div><div class="msg-body"><div class="msg-name">${name}</div><div class="msg-content">${formatContent(content)}</div><div class="msg-time">${t}</div></div>`;messagesContainer.appendChild(div);chatArea.scrollTop=chatArea.scrollHeight;return div}
function formatContent(c){return c.replace(/```(\w*)\n([\s\S]*?)```/g,'<pre><code>$2</code></pre>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\n/g,'<br>')}
function showTyping(){const div=document.createElement('div');div.className='msg msg-ai';div.id='typing-indicator';div.innerHTML='<div class="msg-avatar">A</div><div class="msg-body"><div class="msg-name">Aegis</div><div class="msg-typing"><span></span><span></span><span></span></div></div>';messagesContainer.appendChild(div);chatArea.scrollTop=chatArea.scrollHeight}
function hideTyping(){const el=$('#typing-indicator');if(el)el.remove()}
async function sendMessage(){const text=msgInput.value.trim();const files=[...attachments];if(!text&&!files.length)return;msgInput.value='';msgInput.style.height='auto';btnSend.disabled=true;inputAttachments.innerHTML='';attachments=[];let content=text;if(files.length){files.forEach(f=>{if(f.type.startsWith('image/'))content+=`<br><img src="${f.data}" alt="${f.name}">`;else content+=`<br>📎 ${f.name}`})}if(app.activeChat===null){app.chats.unshift({title:text.slice(0,40)||(files.length?'Media shared':'New Chat'),messages:[],created:Date.now()});app.activeChat=0;topbarTitle.textContent=app.chats[0].title;loadChats()}appendMessage('user',content);app.chats[app.activeChat].messages.push({role:'user',content,time:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})});saveChats();showTyping();const reply=await generateReply(text,files);hideTyping();appendMessage('ai',reply);app.chats[app.activeChat].messages.push({role:'ai',content:reply,time:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})});saveChats()}
async function generateReply(text,files){await new Promise(r=>setTimeout(r,800+Math.random()*1200));const lower=text.toLowerCase();if(files.length&&files[0].type.startsWith('image/'))return'I can see you\'ve shared an image. Visual analysis is ready — describe what you\'d like me to identify or analyze in it.';if(lower.includes('math')||lower.includes('solve')||lower.includes('calculate'))return'Sure, I can help with that.\n\n**Step 1:** Identify the problem type\n**Step 2:** Apply the relevant formula\n**Step 3:** Compute the result\n\nShare the specific problem and I\'ll solve it step by step.';if(lower.includes('code')||lower.includes('program')||lower.includes('debug')||lower.includes('python')||lower.includes('java')||lower.includes('cpp')||lower.includes('javascript'))return'```python\n# Example solution\ndef solve(data):\n    result = []\n    for item in data:\n        processed = item * 2\n        result.append(processed)\n    return result\n\nprint(solve([1, 2, 3]))  # [2, 4, 6]\n```\n\nI support **C++**, **Python**, **Java**, **HTML/CSS**, and **JavaScript**. Share your code or describe the problem and I\'ll help.';if(lower.includes('translate'))return'I support **English**, **Hindi**, **Sanskrit**, **German**, and **Spanish**. Send me the text and target language.';if(lower.includes('generate')||lower.includes('image')||lower.includes('create wallpaper'))return'Image generation is ready. Describe what you\'d like — wallpaper, logo, icon, concept art, or any creative illustration.';if(lower.includes('research')||lower.includes('search')||lower.includes('find'))return'I\'ll research that for you using the internet layer. What specific aspects do you need — sources, summaries, or detailed analysis?';if(lower.includes('call')||lower.includes('dial'))return'Calling requires permission. Enable it in **Settings > Calling**, then say the contact name or number.';if(lower.includes('play')||lower.includes('music')||lower.includes('song'))return'Music control requires gallery permission. Enable it in **Settings > Music Control**, then I can search and play your local music.';if(lower.includes('who are you')||lower.includes('what are you'))return'I\'m **Aegis** — a private AI assistant designed for a small trusted group. I can help with math, coding, research, translation, image analysis, device integration, and more. I operate under strict permission-based access controlled by the owner.';return'Received. I\'m processing your request. Could you provide more details so I can assist you effectively?'}
function saveChats(){localStorage.setItem('aegis_chats',JSON.stringify(app.chats.slice(0,50)))}
msgInput.oninput=()=>{msgInput.style.height='auto';msgInput.style.height=Math.min(msgInput.scrollHeight,150)+'px';btnSend.disabled=!msgInput.value.trim()&&!attachments.length};
msgInput.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage()}};
btnSend.onclick=sendMessage;
$('#btn-new-chat').onclick=()=>{app.activeChat=null;topbarTitle.textContent='New Conversation';welcomeState.classList.remove('hidden');messagesContainer.classList.add('hidden');messagesContainer.innerHTML='';loadChats()};
$$('.quick-action-btn').forEach(b=>b.onclick=()=>{msgInput.value=b.dataset.prompt;msgInput.dispatchEvent(new Event('input'));sendMessage()});
$('#btn-attach').onclick=()=>{const inp=document.createElement('input');inp.type='file';inp.multiple=true;inp.accept='image/*,video/*,audio/*,.pdf,.doc,.docx,.txt,.apk';inp.onchange=e=>{[...e.target.files].forEach(f=>{const reader=new FileReader();reader.onload=ev=>{attachments.push({name:f.name,type:f.type,data:ev.target.result,size:f.size});renderAttachments()};reader.readAsDataURL(f)})};inp.click()};
function renderAttachments(){inputAttachments.innerHTML='';attachments.forEach((a,i)=>{const div=document.createElement('div');div.className='attachment-preview';if(a.type.startsWith('image/'))div.innerHTML=`<img src="${a.data}" alt="${a.name}"><button class="attachment-remove" data-i="${i}">&times;</button>`;else div.innerHTML=`<div style="width:100%;height:100%;display:flex;align-items:center;justify-content:center;font-size:10px;color:var(--text-dim);padding:4px;text-align:center;overflow:hidden">${a.name}</div><button class="attachment-remove" data-i="${i}">&times;</button>`;inputAttachments.appendChild(div)});btnSend.disabled=!msgInput.value.trim()&&!attachments.length;$$('.attachment-remove').forEach(b=>b.onclick=e=>{e.stopPropagation();attachments.splice(+b.dataset.i,1);renderAttachments()})}
$('#btn-user-menu').onclick=e=>{e.stopPropagation();userDropdown.classList.toggle('hidden')};
document.onclick=()=>userDropdown.classList.add('hidden');
$('#btn-settings').onclick=()=>{userDropdown.classList.add('hidden');openModal('modal-settings')};
$('#btn-memory').onclick=()=>{userDropdown.classList.add('hidden');openModal('modal-memory')};
$('#btn-manage-users').onclick=()=>{userDropdown.classList.add('hidden');openModal('modal-users')};
$('#btn-logout').onclick=()=>{app.user=null;app.isOwner=false;app.activeChat=null;appEl.classList.add('hidden');authScreen.classList.remove('hidden');toast('Logged out')};
function loadUsers(){const list=$('#users-list');list.innerHTML='';const stored=JSON.parse(localStorage.getItem('aegis_users')||'[]');const all=[{name:'Sharvil',email:'owner@gmail.com',role:'owner'},...stored];$('#users-count').textContent=`${all.length} / 10 users`;all.forEach((u,i)=>{const div=document.createElement('div');div.className='user-manage-card';div.innerHTML=`<div class="user-avatar">${u.name.charAt(0)}</div><div class="user-manage-info"><div class="user-manage-name">${u.name}</div><div class="user-manage-email">${u.email}</div></div><span class="user-manage-role">${u.role}</span>${u.role!=='owner'?`<div class="user-manage-actions"><button class="btn-remove-user" data-i="${i-1}" title="Remove"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg></button></div>`:''}`;list.appendChild(div)});$$('.btn-remove-user').forEach(b=>b.onclick=()=>{const idx=+b.dataset.i;const users=JSON.parse(localStorage.getItem('aegis_users')||'[]');users.splice(idx,1);localStorage.setItem('aegis_users',JSON.stringify(users));loadUsers();toast('User removed','success')})}
$('#btn-add-user').onclick=()=>$('#add-user-form').classList.toggle('hidden');
$('#btn-cancel-add-user').onclick=()=>$('#add-user-form').classList.add('hidden');
$('#btn-confirm-add-user').onclick=()=>{const email=$('#new-user-email').value.trim();if(!email||!email.includes('@')){toast('Enter a valid email','error');return}const users=JSON.parse(localStorage.getItem('aegis_users')||'[]');if(users.length>=9){toast('Maximum 9 additional users reached','error');return}if(users.find(u=>u.email===email)){toast('Email already added','error');return}users.push({name:email.split('@')[0].replace(/[^a-z]/gi,' ').replace(/\b\w/g,c=>c.toUpperCase()),email,role:'user'});localStorage.setItem('aegis_users',JSON.stringify(users));$('#new-user-email').value='';$('#add-user-form').classList.add('hidden');loadUsers();toast('User added','success')};
$('#btn-clear-memory').onclick=()=>{localStorage.removeItem('aegis_memory');$('#memory-preferences').innerHTML='<span class="memory-tag">No preferences saved yet</span>';$('#memory-context').innerHTML='<span class="memory-tag">No context stored yet</span>';toast('Memory cleared','success')};
$('#btn-camera-input').onclick=async()=>{openModal('modal-camera');try{mediaStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});$('#camera-feed').srcObject=mediaStream}catch(e){toast('Camera access denied','error');closeModal('modal-camera')}};
$('#btn-capture').onclick=()=>{const video=$('#camera-feed');const canvas=document.createElement('canvas');canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext('2d').drawImage(video,0,0);const data=canvas.toDataURL('image/jpeg',0.8);attachments.push({name:'capture.jpg',type:'image/jpeg',data,size:0});renderAttachments();if(mediaStream){mediaStream.getTracks().forEach(t=>t.stop());mediaStream=null}closeModal('modal-camera');toast('Image captured','success')};
const closeCameraModal=()=>{if(mediaStream){mediaStream.getTracks().forEach(t=>t.stop());mediaStream=null}};
$$('[data-modal="modal-camera"]').forEach(b=>b.onclick=()=>{closeCameraModal();closeModal('modal-camera')});
$$('.toggle-input').forEach(t=>{const saved=localStorage.getItem('aegis_perm_'+t.id);if(saved!==null)t.checked=saved==='true';t.onchange=()=>localStorage.setItem('aegis_perm_'+t.id,t.checked)});
const styleSaved=localStorage.getItem('aegis_style');if(styleSaved)$('#setting-response-style').value=styleSaved;$('#setting-response-style').onchange=e=>localStorage.setItem('aegis_style',e.target.value);
const langSaved=localStorage.getItem('aegis_lang');if(langSaved)$('#setting-language').value=langSaved;$('#setting-language').onchange=e=>localStorage.setItem('aegis_lang',e.target.value);
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
